### ISSUE TITLE
Nudge the start time of tracks in the player

### ISSUE THREAD

**Issue by mrjcleaver** [squallooo/MT5#6]
As a follow-up to https://github.com/romainchalut/MT5/issues/34 , I'd like to be able to align tracks that may have be slightly misaligned start times.

![mt5 the html5 multitrack player for musicians 2015-03-08 16-28-30](https://cloud.githubusercontent.com/assets/59202/6547515/630d58da-c5b0-11e4-9bd7-be2ecd5496a5.png)

You can experience the issue here: http://confluence.newchoir.ca:3000 - pick the last song in the drop down.

This said, I think I have other more important requests, so I'm going to expand on them first!

**Comment by micbuffa** [comment]
Ok I thought about it. For your choir maybe MT5 is not the best choice, if
you move the offset of one track, you will need zoom in for accuracy, then
you will need to save the offset or the modified sample server side, people
may break songs like that, etc.

You need a multitrack EDITOR (MT5 is a PLAYER for musicians with loops,
guitar tabs in sync, etc), maybe a tool like this one :
https://blog.hya.io/hya-wave-released/

2015-03-08 21:35 GMT+01:00 Martin Cleaver <notifications@github.com>:

**Comment by mrjcleaver** [comment]
Hi - well, cool. I will take a look at that too.

I assume that the vast majority of the choir will not try to change things, so mt5 is reasonable for them.

I uploaded some of our other training tracks to that install. I'll use it to see if I can get the authors to give me exact start-synced versions.

Thanks, M.
