### ISSUE TITLE
Have you seen Plangular?

### ISSUE THREAD

**Issue by mrjcleaver** [squallooo/MT5#7]
Just FYI - https://github.com/jxnblk/plangular - this is a toolkit for building custom players for SoundCloud. You might be able to leverage some of their ideas, such as the use of AngularJS.

**Comment by mrjcleaver** [comment]
Per #8 , closing

**Comment by mrjcleaver** [comment]
Mic - I appreciate you tried and dislike Angular, and that you know Angular well. But - did you try Plangular's setup? I'm just wondering if they came up with something unusually elegant... the reason I originally asked was because they seem to have some momentum behind their project and they are building out the SoundCloud support and may be able to offer a simple API.

**Comment by micbuffa** [comment]
I don't know Plangular. I will get it a look but right now I'm really
overloaded by my regular work, I will look at a soundcloud support and try
to find time to look at Plangular.

I wrote MT5 as a simple demonstration of web audio + to feet my own needs
as a guitarist who wanted a simple way to play along multitrack backtracks.
Adding soundcloud support seems a very good idea, but rewriting the whole
app with angular is not planned, as I have already a V2 with lots of extra
features ont he way, still private, not ready for being public. It will
come with guitar pro support and music tabs in sync + other goodies such as
song metadata for jumping directly and looping on predefined parts...

Ugly screenshot of V2 preview:


​
​

2015-03-22 13:51 GMT+01:00 Martin Cleaver <notifications@github.com>:
